### ISSUE TITLE
Node Example - ms.Symbol is not a constructor

### ISSUE THREAD

**Issue by CDBridger** [spatialillusions/milsymbol#178]
When running the node example (which is also slightly outdated with its naming based off rollup config). I get this error when I try to open the server in my browser that is hosted via node.

`TypeError: ms.Symbol is not a constructor
    at Server.http.createServer (C:\milsymbol\examples\nodejs\index.js:10:16)
    at emitTwo (events.js:126:13)
    at Server.emit (events.js:214:7)
    at parserOnIncoming (_http_server.js:602:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)`

**Comment by spatialillusions** [comment]
The examples in the master branch might be a bit unstable, and I'm looking into making the node example better and the plan is to move it to another repository. However, I do not have any problems starting the sample and running it on my machine.
Does your server start as it should displaying the url to the server?
What version of nodejs are you running?
(And could you exmplain what is outdated with the sample, or provide a pull? Like I said, it works without any problem for me.)

**Comment by spatialillusions** [comment]
Understand the outdated part now, yes, it should import the library as ES6 module instead so that it doesn’t require a built version. 

Was thinking about if it could be the windows path to milsymbol.js that doesn’t work, could you check if milsymbol gets imported at all? (It should log the milsymbol version info when you start the server, otherwise milsymbol isn’t imported.)

**Comment by CDBridger** [comment]
ah yes my mistake, the rolup config doesn't actually create a milsymbol.js I assumed you had renamed it to milstd-umd.js I did not see the milsymbol.development.js.

**Comment by carlocorradini** [comment]
@Fabioni 
The declaration file (.d.ts) is missing the following line:
```ts
export default { Symbol };
```
Typescript does not know that `milsymbol` has a default export and therefore error.

**Comment by carlocorradini** [comment]
The other patch (`package.json`) is to instruct Node.js (if using `type: module`) how to correctly load an ESM module (`import x from "y";`)

**Comment by carlocorradini** [comment]
@Fabioni Your patch needs to be done every time you import `milsymbol`.
Mine patch the library only once and then you can use it without any issue (also in ESM environments)
